---
apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUService
metadata:
  name: snap-controller
  namespace: dpf-operator-system
spec:
  serviceID: snap-controller
  deployInCluster: true
  helmChart:
    source:
      repoURL: oci://$DPF_REGISTRY
      version: $DPF_VERSION
      chart: snap-controller-chart
    values:
      controller:
        image:
          repository: $DPF_REGISTRY/snap-controller
          tag: $DPF_VERSION
        imagePullSecrets: $DPF_IMAGE_PULL_SECRET
        config:
          # required parameter, name of the secret that contains connection
          # details to access the DPU cluster.
          # this secret should be created by the DPUServiceCredentialRequest API.
          dpuClusterSecret: snap-controller-dpu-cluster-credentials
          # controls where to search for StorageVendor and StoragePolicy CRs
          configNamespace: dpf-operator-system
