---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - events
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - kamaji.clastix.io
  resources:
  - tenantcontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nv-ipam.nvidia.com
  resources:
  - ippools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.dpf.nvidia.com
  resources:
  - dpfoperatorconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuservicechains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuservicechains/finalizers
  verbs:
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuservicechains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuserviceinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuserviceinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuserviceinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuserviceipams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuserviceipams/finalizers
  verbs:
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuserviceipams/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - svc.dpf.nvidia.com
  resources:
  - dpudeployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - svc.dpf.nvidia.com
  resources:
  - dpudeployments/finalizers
  verbs:
  - update
- apiGroups:
  - svc.dpf.nvidia.com
  resources:
  - dpuserviceconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - svc.dpf.nvidia.com
  resources:
  - dpuservicecredentialrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - svc.dpf.nvidia.com
  resources:
  - dpuservicecredentialrequests/finalizers
  verbs:
  - update
- apiGroups:
  - svc.dpf.nvidia.com
  resources:
  - dpuservicecredentialrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - svc.dpf.nvidia.com
  resources:
  - dpuservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - svc.dpf.nvidia.com
  resources:
  - dpuservices/finalizers
  verbs:
  - update
- apiGroups:
  - svc.dpf.nvidia.com
  resources:
  - dpuservices/status
  verbs:
  - get
  - patch
  - update
