# permissions for end users to view dpuservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
  name: dpuservice-viewer-role
rules:
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - dpuservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - dpuservices/status
  verbs:
  - get
