apiVersion: provisioning.dpu.nvidia.com/v1alpha1
kind: DPUCluster
metadata:
  name: dpu-cplane-tenant1
  namespace: dpu-cplane-tenant1
spec:
  type: kamaji
  maxNodes: 1000
  version: v1.29.0
  clusterEndpoint:
    # deploy keepalived instances on the nodes that match the given nodeSelector.
    keepalived:
      # for dpf-standalone env, you can set interface to br-dpu
      # for non-standalone env, set interface to the uplink interface
      interface: brens160 
      # for dpf-standalone env, you can set vip to any value
      # for non-standalone env, set vip to a DPU reachable IP. You may need help from the devops team to get a proper IP
      vip: "10.0.110.200"
      # virtualRouterID must be in range [1,255], make sure the given virtualRouterID does not duplicate with any existing keepalived process running on the host
      virtualRouterID: 126
      # nodeSelector specifies where the keepalived daemonset is deployed
      # for dpf-standalone env, the default value for key "node-role.kubernetes.io/master" is "true". For other distributions, it might be ""
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
