{
 "title": "DOCA Platform Foundation Performance",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dpu_conditions",
    "label": "DPU Conditions",
    "query": {
     "query": "label_values(dpu_status_conditions,type)"
    }
   },
   {
    "name": "dpuservice_conditions",
    "label": "DPUService Conditions",
    "query": {
     "query": "label_values(dpuservice_status_conditions,type)"
    }
   },
   {
    "name": "dpfoperatorconfig_conditions",
    "label": "DPFOperatorConfig Conditions",
    "query": {
     "query": "label_values(dpfoperatorconfig_status_conditions,type)"
    }
   },
   {
    "name": "dpuserviceinterface_conditions",
    "label": "DPUServiceInterface Conditions",
    "query": {
     "query": "label_values(dpuserviceinterface_status_conditions,type)"
    }
   },
   {
    "name": "dpuservicechain_conditions",
    "label": "DPUServiceChain Conditions",
    "query": {
     "query": "label_values(dpuservicechain_status_conditions,type)"
    }
   },
   {
    "name": "dpuserviceipam_conditions",
    "label": "DPUServiceIPAM Conditions",
    "query": {
     "query": "label_values(dpuserviceipam_status_conditions,type)"
    }
   },
   {
    "name": "dpudeployment_conditions",
    "label": "DPUDeployment Conditions",
    "query": {
     "query": "label_values(dpudeployment_status_conditions,type)"
    }
   },
   {
    "name": "dpuservicecredentialrequest_conditions",
    "label": "DPUServiceCredentialRequest Conditions",
    "query": {
     "query": "label_values(dpuservicecredentialrequest_status_conditions,type)"
    }
   },
   {
    "name": "dpucluster_conditions",
    "label": "DPUCluster Conditions",
    "query": {
     "query": "label_values(dpucluster_status_conditions,type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Performance > DPFOperatorConfig",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "DPFOperatorConfig time until $dpfoperatorconfig_conditions since creationTimestamp",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "repeat": "dpfoperatorconfig_conditions",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(dpfoperatorconfig_status_condition_last_transition_time{status=\"True\",type=\"$dpfoperatorconfig_conditions\"} - on(uid) group_left () dpfoperatorconfig_created{}) by (uid, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Performance > DPUCluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "DPUCluster time until $dpucluster_conditions since creationTimestamp",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "repeat": "dpucluster_conditions",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(dpucluster_status_condition_last_transition_time{status=\"True\",type=\"$dpucluster_conditions\"} - on(uid) group_left () dpucluster_created{}) by (uid, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Performance > DPUDeployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "DPUDeployment time until $dpudeployment_conditions since creationTimestamp",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "repeat": "dpudeployment_conditions",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(dpudeployment_status_condition_last_transition_time{status=\"True\",type=\"$dpudeployment_conditions\"} - on(uid) group_left () dpudeployment_created{}) by (uid, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Performance > DPUService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "DPUService time until $dpuservice_conditions since creationTimestamp",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "repeat": "dpuservice_conditions",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(dpuservice_status_condition_last_transition_time{status=\"True\",type=\"$dpuservice_conditions\"} - on(uid) group_left () dpuservice_created{}) by (uid, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Performance > DPUServiceCredentialRequest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 }
  },
  {
   "title": "DPUServiceCredentialRequest time until $dpuservicecredentialrequest_conditions since creationTimestamp",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "repeat": "dpuservicecredentialrequest_conditions",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(dpuservicecredentialrequest_status_condition_last_transition_time{status=\"True\",type=\"$dpuservicecredentialrequest_conditions\"} - on(uid) group_left () dpuservicecredentialrequest_created{}) by (uid, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Performance > DPUServiceChain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "DPUServiceChain time until $dpuservicechain_conditions since creationTimestamp",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "repeat": "dpuservicechain_conditions",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(dpuservicechain_status_condition_last_transition_time{status=\"True\",type=\"$dpuservicechain_conditions\"} - on(uid) group_left () dpuservicechain_created{}) by (uid, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Performance > DPUServiceInterface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 }
  },
  {
   "title": "DPUServiceInterface time until $dpuserviceinterface_conditions since creationTimestamp",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "repeat": "dpuserviceinterface_conditions",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(dpuserviceinterface_status_condition_last_transition_time{status=\"True\",type=\"$dpuserviceinterface_conditions\"} - on(uid) group_left () dpuserviceinterface_created{}) by (uid, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Performance > DPUServiceIPAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "DPUServiceIPAM time until $dpuserviceipam_conditions since creationTimestamp",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "repeat": "dpuserviceipam_conditions",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(dpuserviceipam_status_condition_last_transition_time{status=\"True\",type=\"$dpuserviceipam_conditions\"} - on(uid) group_left () dpuserviceipam_created{}) by (uid, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Performance > DPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "DPU time until $dpu_conditions since creationTimestamp",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "repeat": "dpu_conditions",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(dpu_status_condition_last_transition_time{status=\"True\",type=\"$dpu_conditions\"} - on(uid) group_left () dpu_created{}) by (uid, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Conditions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 } },
  {
   "title": "DPFOperatorConfig by conditions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 154 },
   "targets": [
    { "expr": "sum (dpfoperatorconfig_info)", "legendFormat": "All" },
    {
     "expr": "sum(dpfoperatorconfig_status_conditions{status=\"True\"} == 1) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(dpfoperatorconfig_status_conditions{status=\"False\"} == 1) by (type)",
     "legendFormat": "{{type}} (False)"
    }
   ]
  },
  {
   "title": "DPUDeployment by conditions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 154 },
   "targets": [
    { "expr": "sum (dpudeployment_info)", "legendFormat": "All" },
    {
     "expr": "sum(dpudeployment_status_conditions{status=\"True\"} == 1) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(dpudeployment_status_conditions{status=\"False\"} == 1) by (type)",
     "legendFormat": "{{type}} (False)"
    }
   ]
  },
  {
   "title": "DPUService by conditions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 154 },
   "targets": [
    { "expr": "sum (dpuservice_info)", "legendFormat": "All" },
    {
     "expr": "sum(dpuservice_status_conditions{status=\"True\"} == 1) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(dpuservice_status_conditions{status=\"False\"} == 1) by (type)",
     "legendFormat": "{{type}} (False)"
    }
   ]
  },
  {
   "title": "DPUServiceChain by conditions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 154 },
   "targets": [
    { "expr": "sum (dpuservicechain_info)", "legendFormat": "All" },
    {
     "expr": "sum(dpuservicechain_status_conditions{status=\"True\"} == 1) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(dpuservicechain_status_conditions{status=\"False\"} == 1) by (type)",
     "legendFormat": "{{type}} (False)"
    }
   ]
  },
  {
   "title": "DPUServiceInterface by conditions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 162 },
   "targets": [
    { "expr": "sum (dpuserviceinterface_info)", "legendFormat": "All" },
    {
     "expr": "sum(dpuserviceinterface_status_conditions{status=\"True\"} == 1) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(dpuserviceinterface_status_conditions{status=\"False\"} == 1) by (type)",
     "legendFormat": "{{type}} (False)"
    }
   ]
  },
  {
   "title": "DPUServiceIPAM by conditions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 162 },
   "targets": [
    { "expr": "sum (dpuserviceipam_info)", "legendFormat": "All" },
    {
     "expr": "sum(dpuserviceipam_status_condition{status=\"True\"} == 1) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(dpuserviceipam_status_condition{status=\"False\"} == 1) by (type)",
     "legendFormat": "{{type}} (False)"
    }
   ]
  },
  {
   "title": "DPU by conditions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 162 },
   "targets": [
    { "expr": "sum (dpu_info)", "legendFormat": "All" },
    {
     "expr": "sum(dpu_status_conditions{status=\"True\"} == 1) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(dpu_status_conditions{status=\"False\"} == 1) by (type)",
     "legendFormat": "{{type}} (False)"
    }
   ]
  },
  { "title": "Phases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 170 } },
  {
   "title": "DPU by status phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 171 },
   "targets": [
    {
     "expr": "sum(dpu_status_phase == 1) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "BFB by status phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 171 },
   "targets": [
    {
     "expr": "sum(bfb_status_phase == 1) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  }
 ]
}