apiVersion: sfc.dpf.nvidia.com/v1alpha1
kind: ServiceChainSet
metadata:
  labels:
    app.kubernetes.io/name: servicechainset
    app.kubernetes.io/instance: servicechainset-sample
    app.kubernetes.io/part-of: dpf-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dpf-operator
  name: servicechainset-sample
spec:
  # TODO(user): Add fields here
