apiVersion: sfc.dpf.nvidia.com/v1alpha1
kind: ServiceInterfaceSet
metadata:
  labels:
    app.kubernetes.io/name: serviceinterfaceset
    app.kubernetes.io/instance: serviceinterfaceset-sample
    app.kubernetes.io/part-of: dpf-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dpf-operator
  name: serviceinterfaceset-sample
spec:
  # TODO(user): Add fields here
