# permissions for end users to view bfbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
  name: bfb-viewer-role
rules:
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - bfbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - bfbs/status
  verbs:
  - get
