# permissions for end users to edit bfbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
  name: bfb-editor-role
rules:
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - bfbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - bfbs/status
  verbs:
  - get
