apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
  name: dpudevice-viewer-role
rules:
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - dpudevices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - dpudevices/status
  verbs:
  - get