# permissions for end users to view dpusets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
  name: dpuset-viewer-role
rules:
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - dpusets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - dpusets/status
  verbs:
  - get
