image: golang:1.22.1

stages:
  - verify
  - test
  - build

lint:
  stage: verify
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - make lint

verify:
  stage: verify
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    BASE_REV: $CI_MERGE_REQUEST_DIFF_BASE_SHA # Used by the verify-copyright target
    COMPARISON_REV: $CI_COMMIT_SHA # Used by the verify-copyright target
  script:
    -  make verify-generate verify-copyright

build-binaries:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - make binaries

nightly-release:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "schedule" && $NIGHTLY_RELEASE == "true"
      when: always
  variables:
    ## This is a read-only token used for pulling repositories. Defined in the DPF operator CI/CD settings.
    GITLAB_TOKEN: $CI_TOKEN
    TAG: nightly
    REGISTRY: harbor.mellanox.com/cloud-orchestration-dev/dpf
  tags:
    - release
  before_script:
    - docker login harbor.mellanox.com
  script:
    - make docker-build-all docker-push-all
  after_script:
    - ./hack/scripts/slack-notification.sh

test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == "schedule" && $UNIT_TEST == "true"
  script:
    - make test-report
  artifacts:
    when: always
    paths:
      - junit.xml
    reports:
      junit: junit.xml

e2e:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "schedule" && $E2E_TEST == "true"
      when: always
  variables:
    REGISTRY: localhost:5000
    MINIKUBE_DRIVER: docker
  tags:
    - e2e
  before_script:
    - make clean-test-env test-env-e2e
  script:
    - make generate test-deploy-operator test-e2e
  after_script:
    - ./hack/scripts/slack-notification.sh
    -  make clean-test-env
