image: golang:1.22

workflow:
  # This variable can be defined where the job is triggered. e.g. the pipeline schedule in the gitlab UI
  name: $CI_PIPELINE_NAME

variables:
  ## This is a read-only token used for pulling repositories. Defined in the DPF operator CI/CD settings.
  GITLAB_TOKEN: $CI_TOKEN
  GITLAB_API_TOKEN: $API_READ_TOKEN

stages:
  - verify
  - test
  - build
  - triage

lint:
  stage: verify
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    GOLANGCI_LINT_CACHE: $CI_PROJECT_DIR/.golangci-cache
    GOPATH: $CI_PROJECT_DIR/.gocache # avoid refetching all the packages golangci-lint requires
    # TODO: Remove this one when bug upstream is fixed. golangci-lint should not rely on GOCACHE and instead use
    # GOLANGCI_LINT_CACHE for all of its caching.
    GOCACHE: $CI_PROJECT_DIR/.gocache/go-build # avoid rebuilding all the artifacts golangci-lint requires
  cache:
    key: lint
    untracked: true
    when: always
    paths:
      - hack/tools/bin
      - .gocache
      - .golangci-cache
  before_script:
    # Create the directory which is used to cache golangci-lint results.
    # Added to .gitignore.
    - mkdir -p .golangci-cache
    # Create the directory which will be used as the gocache.
    # Added to .gitignore.
    # Required by golangci-lint to cache go mods
    - mkdir -p .gocache
  script:
    - make lint
    - make lint-helm

verify:
  stage: verify
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    BASE_REV: $CI_MERGE_REQUEST_DIFF_BASE_SHA # Used by the verify-copyright target
    COMPARISON_REV: $CI_COMMIT_SHA # Used by the verify-copyright target
    GOPATH: $CI_PROJECT_DIR/.gocache
  cache:
    key: verify
    untracked: true
    when: always
    paths:
      - hack/tools/bin
      - hack/repos
      - .gocache
  before_script:
    # Create the directory which will be used as the gocache.
    # Added to .gitignore.
    - mkdir -p .gocache
  script:
    -  make verify-generate verify-copyright
  after_script:
    - git diff

test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == "schedule" && $UNIT_TEST == "true"
  variables:
    GOPATH: $CI_PROJECT_DIR/.gocache
  cache:
    key: test
    untracked: true
    when: always
    paths:
      - hack/tools/bin
      - .gocache
  artifacts:
    when: always
    paths:
      - junit.xml
    reports:
      junit: junit.xml
  before_script:
    # Create the directory which will be used as the gocache.
    # Added to .gitignore.
    - mkdir -p .gocache
  script:
    - make test-report

nightly-release:
  stage: build
  needs: [ ]
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "schedule" && $NIGHTLY_RELEASE == "true"
      when: always
  variables:
    # Note: This job is generic to allow it to use both harbor and nvcr.io registries. Variables defined under https://gitlab-master.nvidia.com/doca-platform-foundation/dpf-operator/-/pipeline_schedules define the specific behaviour.
    TAG: v0.0.0-$CI_COMMIT_SHORT_SHA
  tags:
    - release
  before_script:
    - docker login $REGISTRY_SHORT_NAME
  script:
    - make release
  after_script:
    - ./hack/scripts/slack-notification.sh

e2e:
  stage: test
  needs: [ ]
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "schedule" && $E2E_TEST == "true"
      when: always
  variables:
    # The helm bundles and operator-sdk require a remote repository in the e2e environment.
    REGISTRY: gitlab-master.nvidia.com:5005/doca-platform-foundation/dpf-operator/e2e
    IMAGE_PULL_KEY: $GITLAB_REGISTRY_TOKEN
    # Flannel chosen here as it is not hosted on docker hub helping avoid rate limits.
    MINIKUBE_CNI: flannel
    MINIKUBE_DRIVER: docker
    ARTIFACTS: $CI_PROJECT_DIR/artifacts
  tags:
    - e2e
  cache:
    key: e2e
    untracked: true
    when: always
    paths:
      - hack/tools/bin
      - hack/repos
  artifacts:
    when: always
    paths:
      - artifacts/*
  before_script:
    # artifacts are not correctly delete when gitlab restarts jobs.
    - rm -rf artifacts
    - make clean-test-env generate test-env-e2e || go run hack/tools/resource-collector/main.go --kubeconfig ~/.kube/config  --artifactsDirectory $ARTIFACTS
  script:
    # If make-deploy-operator fails run the log collector to see the state of the cluster. This is the same log collector that runs during failing tests.
    - make test-deploy-operator-kustomize || go run hack/tools/resource-collector/main.go --kubeconfig ~/.kube/config  --artifactsDirectory $ARTIFACTS
    - make test-e2e
  after_script:
    - ./hack/scripts/slack-notification.sh
    - make test-cache-images
    - make clean-test-env

triage:
  stage: triage
  needs: []
  variables:
    # This is the name of the pipeline being triaged. Must match the name of the pipeline in Gitlab.
    TRIAGE_PIPELINE_NAME: "Periodic unit test"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $TRIAGE_E2E == "true"
      when: always
  image: registry.gitlab.com/gitlab-ci-utils/curl-jq:2.0.0
  script:
    - ./hack/scripts/periodic_test_triage.sh
