image: golang:1.22.1

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - verify
  - test
  - build

lint:
  stage: verify
  script:
    - make lint

verify:
  stage: verify
  variables:
    BASE_REV: $CI_MERGE_REQUEST_DIFF_BASE_SHA # Used by the verify-copyright target
    COMPARISON_REV: $CI_COMMIT_SHA # Used by the verify-copyright target
  script:
    -  make verify-generate verify-copyright

test:
  stage: test
  script:
    - make test

build-binaries:
  stage: build
  script:
    - make binaries

e2e:
  stage: test
  when: manual
  variables:
    REGISTRY: localhost:5000
    MINIKUBE_DRIVER: docker
  tags:
    - e2e
  before_script:
    - make test-env-e2e
  script:
    - make test-deploy-dpuservice && make test-e2e
  after_script:
    -  make clean-test-env
