image: golang:1.22.0

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - lint
  - test
  - build

lint:
  stage: lint
  script:
    - make lint

verify-generate:
  stage: lint
  script:
    - make verify-generate

test:
  stage: test
  script:
    - make test

build-binaries:
  stage: build
  script:
    - make binaries

e2e:
  stage: test
  when: manual
  variables:
    REGISTRY: localhost:5000
    MINIKUBE_DRIVER: docker
  tags:
    - e2e
  before_script:
    - make test-env-e2e
  script:
    - make test-deploy-dpuservice && make test-e2e
  after_script:
    -  make clean-test-env
