run:
  deadline: 5m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - exportloopref
    - ginkgolinter
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
linters-settings:
  lll:
    line-length: 140
  ginkgolinter:
    forbid-focus-container: true
issues:
  exclude-use-default: false
