run:
  deadline: 5m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - exportloopref
    - gci
    - ginkgolinter
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  gci:
    sections:
      - standard # Standard packages.
      - prefix(gitlab-master.nvidia.com/doca-platform-foundation/dpf-operator) # Packages from this go module.
      - default # All other packages.
    custom-order: true
  ginkgolinter:
    forbid-focus-container: true
  importas:
    no-unaliased: true
    alias:
      # DPF
      - pkg: gitlab-master.nvidia.com/doca-platform-foundation/dpf-operator/api/operator/v1alpha1
        alias: operatorv1
      - pkg: gitlab-master.nvidia.com/doca-platform-foundation/dpf-operator/api/servicechain/v1alpha1
        alias: sfcv1
      - pkg: gitlab-master.nvidia.com/doca-platform-foundation/dpf-operator/api/controlplane/v1alpha1
        alias: controlplanev1
      - pkg:  gitlab-master.nvidia.com/doca-platform-foundation/dpf-operator/api/dpuservice/v1alpha1
        alias: dpuservicev1
      - pkg: gitlab-master.nvidia.com/doca-platform-foundation/dpf-operator/internal/operator/controllers
        alias: operatorcontroller
      - pkg: gitlab-master.nvidia.com/doca-platform-foundation/dpf-operator/internal/servicechainset/controllers
        alias: sfcsetcontroller        
      - pkg: gitlab-master.nvidia.com/doca-platform-foundation/dpf-operator/internal/dpuservice/controllers
        alias: dpuservicecontroller
      - pkg: gitlab-master.nvidia.com/doca-platform-foundation/dpf-operator/internal/argocd/api/application/v1alpha1
        alias: argov1
      - pkg: gitlab-master.nvidia.com/doca-platform-foundation/dpf-operator/internal/controlplane/metadata
        alias: controlplanemeta
      - pkg: gitlab-master.nvidia.com/doca-platform-foundation/dpf-operator/internal/cniprovisioner/dpu/config
        alias: dpucniprovisionerconfig
      - pkg: gitlab-master.nvidia.com/doca-platform-foundation/dpf-operator/internal/cniprovisioner/host/config
        alias: hostcniprovisionerconfig

        # Kubernetes
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/api/apps/v1
        alias: appsv1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: apierrors
      - pkg: k8s.io/apimachinery/pkg/util/errors
        alias: kerrors
      - pkg: k8s.io/component-base/logs/api/v1
        alias: logsv1
      - pkg: k8s.io/utils/exec
        alias: kexec
      - pkg: k8s.io/api/admissionregistration/v1
        alias: admissionregistrationv1
      - pkg: k8s.io/api/rbac/v1
        alias: rbacv1

      # Controller Runtime
      - pkg: sigs.k8s.io/controller-runtime
        alias: ctrl

issues:
  exclude-use-default: false
