run:
  deadline: 5m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - exportloopref
    - gci
    - ginkgolinter
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  lll:
    line-length: 140
  gci:
    sections:
      - standard # Standard packages.
      - prefix(gitlab-master.nvidia.com/doca-platform-foundation/dpf-operator) # Packages from this go module.
      - default # All other packages.
    custom-order: true
  ginkgolinter:
    forbid-focus-container: true

issues:
  exclude-use-default: false
