ARG base_image

FROM docker.io/library/golang:1.19 AS ovnkubernetes-builder

WORKDIR /workspace
RUN apt update && apt install -y make git
ARG ovn_kubernetes_dir
COPY ${ovn_kubernetes_dir} ovn-kubernetes
RUN cd ovn-kubernetes/go-controller && \
    make

FROM ${base_image}

COPY --from=ovnkubernetes-builder /workspace/ovn-kubernetes/go-controller/_output/go/bin/ovnkube /usr/bin/ovnkube
