ARG base_image

FROM --platform=${TARGETPLATFORM} docker.io/library/golang:1.19 as ovnkubernetes-builder

WORKDIR /workspace
RUN apt update && apt install -y make git
COPY hack/repos/ovn-kubernetes ovn-kubernetes
ARG ovn_kubernetes_branch
RUN cd ovn-kubernetes/go-controller && \
    git checkout origin/${ovn_kubernetes_branch} && \
    make

FROM --platform=${TARGETPLATFORM} ${base_image}

COPY --from=ovnkubernetes-builder /workspace/ovn-kubernetes/go-controller/_output/go/bin/ovnkube /usr/bin/ovnkube
