# Build the manager binary
FROM golang:1.22 as builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace

RUN wget https://cdn.dl.k8s.io/release/v1.29.3/bin/linux/amd64/kubeadm && chmod +x kubeadm
RUN mkdir -p /kubeconfig

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY cmd/provisioning/main.go cmd/provisioning/main.go
COPY api/provisioning/ api/provisioning/
COPY internal/provisioning/controllers/ internal/provisioning/controllers/

# Build
# the GOARCH has not a default value to allow the binary be built according to the host where the command
# was called. For example, if we call make docker-build in a local env which has the Apple Silicon M1 SO
# the docker BUILDPLATFORM arg will be linux/arm64 when for Apple x86 it will be linux/amd64. Therefore,
# by leaving it empty we can ensure that the container and binary shipped on it will have the same platform.
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o provisioning-manager cmd/provisioning/main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:debug
WORKDIR /
COPY --from=builder /workspace/provisioning-manager .
COPY --from=builder /workspace/kubeadm /bin
COPY --from=builder /kubeconfig /kubeconfig
# USER 65532:65532

ENTRYPOINT ["/provisioning-manager"]
