apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: dpf-operator

profiles:
  - name: dpuservice
    build:
      local:
        useBuildkit: true
      artifacts:
        - image: nvidia/dpuservice-controller
          runtimeType: go
          docker:
            buildArgs:
              ## Used for debugging. Disable inlining and optimizations in the go compiler. Passed to go build using `-gcflags`
              GCFLAGS: "all=-N -l"
              target_arch: "arm64"
              package: ./cmd/dpuservice
              builder_image: golang:1.21.7
              base_image: gcr.io/distroless/static:nonroot
            dockerfile: Dockerfile
    manifests:
      ## Deploy the manager.
      kustomize:
        paths:
          - config/dpuservice/default
    portForward:
      - resourceType: deployment
        resourceName: dpuservice-controller-manager
        namespace: dpuservice-controller-system
        port: 56268
        localPort: 8080
        address: 0.0.0.0
