apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: dpf-operator

profiles:
  - name: dpuservice
    build:
      local:
        useBuildkit: true
      artifacts:
        - image: nvidia.com/dpuservice-controller-manager
          runtimeType: go
          docker:
            buildArgs:
              ## Used for debugging. Disable inlining and optimizations in the go compiler. Passed to go build using `-gcflags`
              GCFLAGS: "all=-N -l"
              target_arch: "arm64"
              package: ./cmd/dpuservice
              builder_image: golang:1.22
              base_image: gcr.io/distroless/static:nonroot
            dockerfile: Dockerfile
    manifests:
      ## Deploy the manager.
      kustomize:
        paths:
          - config/dpuservice/default
    portForward:
      - resourceType: deployment
        resourceName: dpuservice-controller-manager
        namespace: dpuservice-controller-system
        port: 56268
        localPort: 8080
        address: 0.0.0.0
  - name: operator
    # Note: The operator profile is mutually exclusive with other profiles as the operator will deploy the other components.
    build:
      local:
        useBuildkit: true
      artifacts:
        - image: nvidia.com/dpf-operator-controller-manager
          runtimeType: go
          docker:
            buildArgs:
              ## Used for debugging. Disable inlining and optimizations in the go compiler. Passed to go build using `-gcflags`
              gcflags: "all=-N -l"
              ldflags: "-extldflags '-static'"
              target_arch: "arm64"
              package: ./cmd/operator
              builder_image: golang:1.22
              base_image: gcr.io/distroless/static:nonroot
            dockerfile: Dockerfile
    manifests:
      ## Deploy the manager.
      kustomize:
        paths:
          - config/operator/default
          # Deploy CRDs for components deployed by the operator.
          - config/dpuservice/crd
          - config/dpuservice/crd
          - config/servicechainset/crd
          - config/dpf-provisioning/crd
          - config/argocd/crd
    portForward:
      - resourceType: deployment
        resourceName: dpf-operator-controller-manager
        namespace: dpf-operator-system
        port: 56268
        localPort: 8082
        address: 0.0.0.0
      - resourceType: deployment
        resourceName: dpuservice-controller-manager
        namespace: dpuservice-controller-system
        port: 56268
        localPort: 8081
        address: 0.0.0.0

