ARG TARGETARCH
ARG hbn_nvcr_tag

FROM nvcr.io/nvidia/doca/doca_hbn:${hbn_nvcr_tag}

RUN apt update && \
    apt install -y python3-pyinotify

WORKDIR /workspace

COPY ovs-watcher.py ovs-watcher.py

ENTRYPOINT ["python3", "/workspace/ovs-watcher.py"]
