apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-device-plugin
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "sriov-device-plugin.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.sriovDevicePlugin.serviceAccount.annotations | nindent 4 }}