---
apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUServiceIPAM
metadata:
  name: spdk-pool
  namespace: dpf-operator-system
spec:
  metadata:
    labels:
      svc.dpu.nvidia.com/pool: spdk-pool
  ipv4Subnet:
    subnet: "10.44.44.0/24"
    gateway: "10.44.44.1"
    perNodeIPCount: 20
