apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUService
metadata:
  name: snap-dpu
  namespace: dpf-operator-system
spec:
  helmChart:
    source:
      repoURL: oci://gitlab-master.nvidia.com:5005/pengwang/workspace
      version: v0.1.0
      chart: snap-dpu-chart
    values:
      docaSnap:
        env:
          SPDK_XLIO_PATH: "" # e.g., "/usr/lib/libxlio.so" to enable XLIO
          APP_ARGS: ""       # e.g., "--wait-for-rpc"
          SPDK_RPC_INIT_CONF_JSON: ""  # e.g., "/etc/nvda_snap/config.json"
          SPDK_RPC_INIT_CONF: ""       # e.g., "/etc/nvda_snap/spdk_rpc_init.conf"
          SNAP_RPC_INIT_CONF: ""       # e.g., "/etc/nvda_snap/snap_rpc_init.conf"
      snapNodeDriver:
        image:
          repository: gitlab-master.nvidia.com:5005/pengwang/workspace/snap-node-driver
          tag: v0.1.0
      storagePlugin:
        image:
          repository: gitlab-master.nvidia.com:5005/pengwang/workspace/storage-vendor-dpu-plugin
          tag: v0.1.0
      # RBAC roles for clients from host cluster
      # serviceAccount names must be aligned with the serviceAccount names from DPUServiceCredentialRequest
      rbacRoles:
        snapCsiPlugin:
          serviceAccount: snap-csi-plugin-sa
        snapController:
          serviceAccount: snap-controller-sa
