apiVersion: sfc.dpf.nvidia.com/v1alpha1
kind: ServiceChain
metadata:
  name: svc-chain-test
  namespace: default
spec:
  spec:
    switches:
      - ports:
        - serviceInterface:
            matchLabels:
              uplink: p0
        - service:
            matchLabels:
              # labels on pod
              # TODO do we need to match, isn't pf0vf0_sf enough
              sfc.nvidia.com/service: hbn
            interface: pf0vf0_sf
      - ports:
        - service:
            # TODO what does reference mean? How do we match on it?
            reference:
              name: hbn
            interface: tail-iface
        - service:
            matchLabels:
              sfc.nvidia.com/service: fw1
            interface: pf1vf0_sf