apiVersion: sfc.dpf.nvidia.com/v1alpha1
kind: ServiceChain
metadata:
  name: svc-chain-test
  namespace: default
spec:
  switches:
    - ports:
      - service:
          matchLabels:
            sfc.nvidia.com/service: hbn
          interface: net1
      - serviceInterface:
          matchLabels:
            uplink: port0
      - service:
          matchLabels:
            sfc.nvidia.com/service: hbn
          interface: net2
    - ports:
      - serviceInterface:
          matchLabels:
            uplink: p0
      - service:
          matchLabels:
            sfc.nvidia.com/service: hbn
          interface: net2
  node: k8smaster
