apiVersion: controlplane.dpf.nvidia.com/v1alpha1
kind: DPFCluster
metadata:
  labels:
    app.kubernetes.io/name: dpfcluster
    app.kubernetes.io/instance: dpfcluster-sample
    app.kubernetes.io/part-of: dpf-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dpf-operator
  name: dpfcluster-sample
spec:
  # TODO(user): Add fields here
