---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - dpuserviceinterfaces
  - isolationclasses
  - serviceinterfaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - dpuvirtualnetworks
  - dpuvpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - dpuvirtualnetworks/finalizers
  - dpuvpcs/finalizers
  verbs:
  - update
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - dpuvirtualnetworks/status
  - dpuvpcs/status
  verbs:
  - get
  - patch
  - update
