apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dpf-operator
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dpf-operator
    app.kubernetes.io/part-of: dpf-operator
    app.kubernetes.io/version: 0.1.0
    dpu.nvidia.com/component: dpf-operator-controller-manager
    helm.sh/chart: dpf-operator-0.1.0
  name: dpf-operator-manager-rolebinding-openshift
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: dpf-operator-controller-manager
  namespace: dpf-operator-system
