apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.dpf.nvidia.com/v1alpha1",
          "kind": "DPFOperatorConfig",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "dpf-operator",
              "app.kubernetes.io/instance": "dpfoperatorconfig-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "dpfoperatorconfig",
              "app.kubernetes.io/part-of": "dpf-operator"
            },
            "name": "dpf-operator-dpfoperatorconfig",
            "namespace": "dpf-operator"
          },
          "spec": {
            "hostNetworkConfiguration": {
              "cidr": "10.0.96.0/20",
              "hostPF0": "ens2f0np0",
              "hostPF0VF0": "enp23s0f0v0",
              "hosts": [
                {
                  "dpuClusterNodeName": "dpu-worker-1",
                  "dpuIP": "10.0.96.20/24",
                  "gateway": "10.0.96.254",
                  "hostClusterNodeName": "ocp-worker-1",
                  "hostIP": "10.0.96.10/24"
                },
                {
                  "dpuClusterNodeName": "dpu-worker-2",
                  "dpuIP": "10.0.97.20/24",
                  "gateway": "10.0.97.254",
                  "hostClusterNodeName": "ocp-worker-2",
                  "hostIP": "10.0.97.10/24"
                }
              ]
            },
            "provisioningConfiguration": {
              "bfbPVCName": "dpf-provisioning-volume",
              "imagePullSecret": "fake-name"
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-05-15T11:42:47Z"
    operators.operatorframework.io/builder: operator-sdk-v1.34.1
    operators.operatorframework.io/project_layout: unknown
  name: dpf-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Application
      name: applications.argoproj.io
      version: v1alpha1
    - kind: ApplicationSet
      name: applicationsets.argoproj.io
      version: v1alpha1
    - kind: AppProject
      name: appprojects.argoproj.io
      version: v1alpha1
    - kind: Bfb
      name: bfbs.provisioning.dpf.nvidia.com
      version: v1alpha1
    - kind: DPFOperatorConfig
      name: dpfoperatorconfigs.operator.dpf.nvidia.com
      version: v1alpha1
    - kind: Dpu
      name: dpus.provisioning.dpf.nvidia.com
      version: v1alpha1
    - kind: DPUServiceChain
      name: dpuservicechains.sfc.dpf.nvidia.com
      version: v1alpha1
    - kind: DPUServiceInterface
      name: dpuserviceinterfaces.sfc.dpf.nvidia.com
      version: v1alpha1
    - kind: DPUServiceIPAM
      name: dpuserviceipams.sfc.dpf.nvidia.com
      version: v1alpha1
    - kind: DPUService
      name: dpuservices.svc.dpf.nvidia.com
      version: v1alpha1
    - kind: DpuSet
      name: dpusets.provisioning.dpf.nvidia.com
      version: v1alpha1
    - kind: ServiceChain
      name: servicechains.sfc.dpf.nvidia.com
      version: v1alpha1
    - kind: ServiceChainSet
      name: servicechainsets.sfc.dpf.nvidia.com
      version: v1alpha1
    - kind: ServiceInterface
      name: serviceinterfaces.sfc.dpf.nvidia.com
      version: v1alpha1
    - kind: ServiceInterfaceSet
      name: serviceinterfacesets.sfc.dpf.nvidia.com
      version: v1alpha1
  description: Dpf Operator description. TODO.
  displayName: Dpf Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: dpf-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: dpf-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: dpf-operator
          control-plane: controller-manager
        name: dpf-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - command:
                - /manager
                image: nvidia.com/dpf-operator-controller-manager:v0.0.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources: {}
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              serviceAccountName: dpf-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: dpf-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - dpf-operator
  links:
  - name: Dpf Operator
    url: https://dpf-operator.domain
  maintainers:
  - email: your@email.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  version: 0.0.0
