apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.dpf.nvidia.com/v1alpha1",
          "kind": "DPFOperatorConfig",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "dpf-operator",
              "app.kubernetes.io/instance": "dpfoperatorconfig-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "dpfoperatorconfig",
              "app.kubernetes.io/part-of": "dpf-operator"
            },
            "name": "dpf-operator-dpfoperatorconfig",
            "namespace": "dpf-operator"
          },
          "spec": {
            "hostNetworkConfiguration": {
              "CIDR": "10.0.96.0/20",
              "hosts": [
                {
                  "dpuClusterNodeName": "dpu-worker-1",
                  "dpuIP": "10.0.96.20/24",
                  "gateway": "10.0.96.254",
                  "hostClusterNodeName": "ocp-worker-1",
                  "hostIP": "10.0.96.10/24"
                },
                {
                  "dpuClusterNodeName": "dpu-worker-2",
                  "dpuIP": "10.0.97.20/24",
                  "gateway": "10.0.97.254",
                  "hostClusterNodeName": "ocp-worker-2",
                  "hostIP": "10.0.97.10/24"
                }
              ]
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-04-24T10:23:41Z"
    operators.operatorframework.io/builder: operator-sdk-v1.34.1
    operators.operatorframework.io/project_layout: unknown
  name: dpf-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: DPFOperatorConfig
      name: dpfoperatorconfigs.operator.dpf.nvidia.com
      version: v1alpha1
    - kind: DPUService
      name: dpuservices.svc.dpf.nvidia.com
      version: v1alpha1
  description: Dpf Operator description. TODO.
  displayName: Dpf Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - validatingwebhookconfigurations
          verbs:
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - daemonsets
          - deployments
          verbs:
          - create
          - get
          - list
          - patch
          - watch
        - apiGroups:
          - argoproj.io
          resources:
          - applications
          - appprojects
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          - events
          - persistentvolumeclaims
          - secrets
          - serviceaccounts
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          - serviceaccounts
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - nodes
          - secrets
          verbs:
          - get
          - list
          - patch
          - watch
        - apiGroups:
          - events.k8s.io
          resources:
          - events
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - kamaji.clastix.io
          resources:
          - tenantcontrolplanes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - operator.dpf.nvidia.com
          resources:
          - dpfoperatorconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operator.dpf.nvidia.com
          resources:
          - dpfoperatorconfigs/finalizers
          verbs:
          - update
        - apiGroups:
          - operator.dpf.nvidia.com
          resources:
          - dpfoperatorconfigs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          - rolebindings
          - roles
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - svc.dpf.nvidia.com
          resources:
          - dpuservices
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - svc.dpf.nvidia.com
          resources:
          - dpuservices/finalizers
          verbs:
          - update
        - apiGroups:
          - svc.dpf.nvidia.com
          resources:
          - dpuservices/status
          verbs:
          - get
          - patch
          - update
        serviceAccountName: dpf-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: dpf-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: dpf-operator
          control-plane: controller-manager
        name: dpf-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - reconcileOVNKubernetes=true
                command:
                - /manager
                image: nvidia.com/operator-controller-manager:v0.0.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources: {}
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              serviceAccountName: dpf-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: dpf-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - dpf-operator
  links:
  - name: Dpf Operator
    url: https://dpf-operator.domain
  maintainers:
  - email: your@email.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  version: 0.0.0
