apiVersion: operator.dpf.nvidia.com/v1alpha1
kind: DPFOperatorConfig
metadata:
  labels:
    app.kubernetes.io/name: dpfoperatorconfig
    app.kubernetes.io/instance: dpfoperatorconfig-sample
    app.kubernetes.io/part-of: dpf-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dpf-operator
  name: dpfoperatorconfig
  namespace: dpf-operator-system
spec:
  hostNetworkConfiguration:
    hostIPs:
      dpf-worker-0: 192.168.1.1/24
      dpf-worker-1: 192.168.1.2/24
    dpuIPs:
      co-node-34-dpu-oob: 192.168.1.10/24
      co-node-35-dpu-oob: 192.168.1.11/24
