apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ovs-cni.fullname" . }}-marker-crb
  labels:
  {{- include "ovs-cni.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "ovs-cni.fullname" . }}-marker-cr'
subjects:
- kind: ServiceAccount
  name: '{{ include "ovs-cni.fullname" . }}-marker'
  namespace: '{{ .Release.Namespace }}'