apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ovs-cni.fullname" . }}-marker
  labels:
  {{- include "ovs-cni.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.marker.serviceAccount.annotations | nindent 4 }}