imagePullSecrets: []
kubeMultusDs:
  installMultusBinary:
    containerSecurityContext:
      privileged: true
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v4.0.2
    resources:
      requests:
        cpu: 10m
        memory: 15Mi
  kubeMultus:
    containerSecurityContext:
      privileged: true
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v4.0.2
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 50Mi
kubernetesClusterDomain: cluster.local
multus:
  serviceAccount:
    annotations: {}
multusDaemonConfig:
  daemonConfigJson: |-
    {
        "chrootDir": "/hostroot",
        "cniVersion": "0.3.1",
        "logLevel": "verbose",
        "logToStderr": true,
        "cniConfigDir": "/host/etc/cni/net.d",
        "multusAutoconfigDir": "/host/etc/cni/net.d",
        "multusConfigFile": "auto",
        "socketDir": "/host/run/multus/"
    }
networkAttachmentBrSFCJson: |-
    {
      "cniVersion": "0.4.0",
      "type": "ovs",
      "bridge": "br-sfc",
      "mtu": 1500,
      "interface_type": "dpdk",
      "ipam": {
        "type": "static"
      }
    }
networkAttachmentBrHBNJson: |-
    {
      "cniVersion": "0.4.0",
      "type": "ovs",
      "mtu": 1500,
      "bridge": "br-hbn",
      "interface_type": "dpdk"
    }
