apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hbn.fullname" . }}-hbn-nodes-conf
  labels:
  {{- include "hbn.labels" . | nindent 4 }}
data:
  hbn_nodes_config.json: {{ .Values.hbnNodesConf.hbnNodesConfigJson | toYaml | indent
    1 }}