---
apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUService
metadata:
  name: doca-blueman-service
  namespace: dpf-operator-system
spec:
  helmChart:
    source:
      repoURL: $NGC_HELM_REGISTRY_REPO_URL
      version: 1.0.5
      chart: doca-blueman
