apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dpf-operator-system
namePrefix: dpf-operator-
resources:
  - ../dpuservice/crd
  - ../servicechainset/crd
  - ../provisioning/crd

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      dpu.nvidia.com/component: dpf-operator-controller-manager
