---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nv-ipam.nvidia.com
  resources:
  - cidrpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nv-ipam.nvidia.com
  resources:
  - ippools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - servicechains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - servicechains/finalizers
  verbs:
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - servicechainsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - servicechainsets/finalizers
  verbs:
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - servicechainsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - serviceinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - serviceinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - serviceinterfacesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - serviceinterfacesets/finalizers
  verbs:
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - serviceinterfacesets/status
  verbs:
  - get
  - patch
  - update
