# permissions for end users to view serviceinterfacesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: serviceinterfaceset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dpf-operator
    app.kubernetes.io/part-of: dpf-operator
    app.kubernetes.io/managed-by: kustomize
  name: serviceinterfaceset-viewer-role
rules:
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - serviceinterfacesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - serviceinterfacesets/status
  verbs:
  - get
