{{ if .Values.parca.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parca-debug
rules:
  - nonResourceURLs:
      - "/debug/pprof/*"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: parca-debug
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: parca-debug
subjects:
  - kind: ServiceAccount
    name: {{ .Values.parca.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{ end }}