---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dpf-operator-manager-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - cert-manager.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - nodes
  - persistentvolumeclaims
  - pods
  - pods/exec
  - secrets
  - serviceaccounts
  - serviceaccounts/token
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
- apiGroups:
  - kamaji.clastix.io
  resources:
  - tenantcontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodemaintenance.medik8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - nv-ipam.nvidia.com
  resources:
  - ippools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.dpf.nvidia.com
  resources:
  - dpfoperatorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.dpf.nvidia.com
  resources:
  - dpfoperatorconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - operator.dpf.nvidia.com
  resources:
  - dpfoperatorconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - provisioning.dpf.nvidia.com
  resources:
  - bfbs
  - dpuflavors
  - dpus
  - dpusets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - provisioning.dpf.nvidia.com
  resources:
  - bfbs/finalizers
  - dpuflavors/finalizers
  - dpus/finalizers
  - dpusets/finalizers
  verbs:
  - update
- apiGroups:
  - provisioning.dpf.nvidia.com
  resources:
  - bfbs/status
  - dpus/status
  - dpusets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuservicechains
  - dpuserviceinterfaces
  - dpuserviceipams
  - servicechains
  - serviceinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuservicechains/finalizers
  - dpuserviceinterfaces/finalizers
  - dpuserviceipams/finalizers
  - servicechains/finalizers
  - serviceinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuservicechains/status
  - dpuserviceinterfaces/status
  - dpuserviceipams/status
  - servicechains/status
  - serviceinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - svc.dpf.nvidia.com
  resources:
  - dpudeployments
  - dpuserviceconfigurations
  - dpuservicecredentialrequests
  - dpuservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - svc.dpf.nvidia.com
  resources:
  - dpudeployments/finalizers
  - dpuservicecredentialrequests/finalizers
  - dpuservices/finalizers
  verbs:
  - update
- apiGroups:
  - svc.dpf.nvidia.com
  resources:
  - dpudeployments/status
  - dpuservicecredentialrequests/status
  - dpuservices/status
  verbs:
  - get
  - patch
  - update
