{{- $isWebhookEnabled := include "dpf-ovn-kubernetes-operator.isWebhookEnabled" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dpf-ovn-kubernetes-operator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: dpf-operator
    app.kubernetes.io/part-of: dpf-operator
    control-plane: controller-manager
    dpf.nvidia.com/component: dpf-ovn-kubernetes-operator-controller-manager
  {{- include "dpf-ovn-kubernetes-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
      dpf.nvidia.com/component: dpf-ovn-kubernetes-operator-controller-manager
    {{- include "dpf-ovn-kubernetes-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
        dpf.nvidia.com/component: dpf-ovn-kubernetes-operator-controller-manager
      {{- include "dpf-ovn-kubernetes-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args: {{- toYaml .Values.controllerManager.manager.args | nindent 8 }}
        command:
        - /manager
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.controllerManager.manager.containerSecurityContext
          | nindent 10 }}
        {{- if eq $isWebhookEnabled "true" }}
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        {{- end }}
      imagePullSecrets: {{ .Values.imagePullSecrets | default list | toJson }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "dpf-ovn-kubernetes-operator.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
      {{- with .Values.controllerManager.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllerManager.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if eq $isWebhookEnabled "true" }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "dpf-ovn-kubernetes-operator.webhook.secretName" . }}
      {{- end }}
