{{- $isWebhookEnabled := include "dpf-ovn-kubernetes-operator.isWebhookEnabled" . -}}
{{- if eq $isWebhookEnabled "true" }}
{{- $issuerName := include "dpf-ovn-kubernetes-operator.fullname" . -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: dpf-operator
    app.kubernetes.io/part-of: dpf-operator
    control-plane: controller-manager
    dpu.nvidia.com/component: dpf-ovn-kubernetes-operator-webhook
    {{- include "dpf-ovn-kubernetes-operator.labels" . | nindent 4 }}
  name: {{ $issuerName }}
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: dpf-operator
    app.kubernetes.io/part-of: dpf-operator
    control-plane: controller-manager
    dpu.nvidia.com/component: dpf-ovn-kubernetes-operator-webhook
    {{- include "dpf-ovn-kubernetes-operator.labels" . | nindent 4 }}
  name: {{ include "dpf-ovn-kubernetes-operator.webhook.certificateName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ include "dpf-ovn-kubernetes-operator.webhook.serviceName" . }}.{{ .Release.Namespace }}.svc
  - {{ include "dpf-ovn-kubernetes-operator.webhook.serviceName" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ $issuerName }}
  secretName: {{ include "dpf-ovn-kubernetes-operator.webhook.secretName" . }}
{{- end }}
