apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/created-by: dpf-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: host-cni-provisioner
    app.kubernetes.io/part-of: dpf-operator
  name: host-cni-provisioner
  namespace: dpf-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: host-cni-provisioner-scc
  namespace: dpf-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: host-cni-provisioner
  namespace: dpf-operator-system
---
apiVersion: v1
data:
  config.yaml: null
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/created-by: dpf-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: host-cni-provisioner
    app.kubernetes.io/part-of: dpf-operator
  name: host-cni-provisioner
  namespace: dpf-operator-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/created-by: dpf-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: host-cni-provisioner
    app.kubernetes.io/part-of: dpf-operator
  name: host-cni-provisioner
  namespace: dpf-operator-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: host-cni-provisioner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: host-cni-provisioner
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: nvidia.com/host-cni-provisioner:v0.0.0
        imagePullPolicy: Always
        name: host-cni-provisioner
        readinessProbe:
          exec:
            command:
            - cat
            - /var/run/readyz
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/dpf
          name: fakefs
        - mountPath: /var/lib/ovn-ic
          name: ovndb
        - mountPath: /etc/hostcniprovisioner
          name: config
      hostNetwork: true
      serviceAccountName: host-cni-provisioner
      volumes:
      - hostPath:
          path: /var/dpf
        name: fakefs
      - hostPath:
          path: /var/lib/ovn-ic
        name: ovndb
      - configMap:
          name: host-cni-provisioner
        name: config
