{{ if not .Values.forDPUCluster }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicechainset-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: dpf-operator
    app.kubernetes.io/part-of: dpf-operator
    control-plane: controller-manager
  {{- include "servicechain.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "servicechain.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "servicechain.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      containers:
      - args: {{- toYaml .Values.controllerManager.manager.args | nindent 8 }}
        command:
        - /servicechainset
        volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 10 }}
        env:
          {{ toYaml .Values.env | nindent 10 }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.controllerManager.manager.containerSecurityContext
          | nindent 10 }}
      imagePullSecrets: {{ .Values.imagePullSecrets | default list | toJson }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: servicechainset-controller-manager
      terminationGracePeriodSeconds: 10
      tolerations:
        - operator: Exists
          effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
        - operator: Exists
          effect: NoSchedule
          key: node-role.kubernetes.io/master
{{ end }}
