{{ if not (quote .Values.dpucluster.name | empty) }}
{{ if not (quote .Values.dpucluster.namespace | empty) }}
{{ if not .Values.forDPUCluster }}
---
apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUServiceCredentialRequest
metadata:
  name: servicesetcontroller
  namespace: dpf-operator-system
spec:
  duration: 24h
  serviceAccount:
    name: servicechainset-controller-manager
    namespace: dpf-operator-system
  targetCluster:
    name: {{ .Values.dpucluster.name }}
    namespace: {{ .Values.dpucluster.namespace }}
  type: tokenFile
  secret:
    name: servicechainset-controller-manager-credentials
    namespace: dpf-operator-system
{{ end }}
{{ end }}
{{ end }}