apiVersion: v1
kind: ServiceAccount
metadata:
  name: dpf-servicechain-controller-manager
  labels:
    app.kubernetes.io/component: rbac
  {{- include "servicechain.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}