apiVersion: v1
kind: ServiceAccount
metadata:
  name: servicechainset-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: rbac
  {{- include "servicechain.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}