apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dpf-operator-system
resources:
- daemonset.yaml
- rbac.yaml
images:
- name: controller
  newName: dev/host-cni-provisioner
  newTag: v0.0.1
