apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dpf-operator-system
resources:
- daemonset.yaml
- rbac.yaml
- configmap.yaml
images:
- name: controller
  newName: example.com/host-cni-provisioner
  newTag: v0.1.0
