controllerManager:
  manager:
    args:
    - --leader-elect
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: nvidia.com/dpf-ovn-kubernetes-operator-controller-manager
      tag: v0.0.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: "Exists"
    effect: NoSchedule
imagePullSecrets: []
config:
  vfResourceName: nil # mellanox-bf3-vf
  hostPF0: "" # ens2f0np0
  hostPF0VF0: "" # enp23s0f0v0
  cidr: "" # 10.0.96.0/20
  hosts: []
#  - hostClusterNodeName: ocp-worker-1
#    dpuClusterNodeName: dpu-worker-1
#    hostIP: 10.0.96.10/24
#    dpuIP: 10.0.96.20/24
#    gateway: 10.0.96.254
#  - hostClusterNodeName: ocp-worker-2
#    dpuClusterNodeName: dpu-worker-2
#    hostIP: 10.0.97.10/24
#    dpuIP: 10.0.97.20/24
#    gateway: 10.0.97.254
