kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "nvidia-k8s-ipam.fullname" . }}-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nvidia-k8s-ipam.fullname" . }}-node
subjects:
  - kind: ServiceAccount
    name: {{ include "nvidia-k8s-ipam.fullname" . }}-node
    namespace: {{ .Release.Namespace }}
