---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - persistentvolumeclaims
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kamaji.clastix.io
  resources:
  - tenantcontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.dpf.nvidia.com
  resources:
  - dpfoperatorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.dpf.nvidia.com
  resources:
  - dpfoperatorconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - operator.dpf.nvidia.com
  resources:
  - dpfoperatorconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - provisioning.dpf.nvidia.com
  resources:
  - bfbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - provisioning.dpf.nvidia.com
  resources:
  - bfbs/finalizers
  verbs:
  - update
- apiGroups:
  - provisioning.dpf.nvidia.com
  resources:
  - bfbs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - provisioning.dpf.nvidia.com
  resources:
  - dpus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - provisioning.dpf.nvidia.com
  resources:
  - dpus/finalizers
  verbs:
  - update
- apiGroups:
  - provisioning.dpf.nvidia.com
  resources:
  - dpus/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - provisioning.dpf.nvidia.com
  resources:
  - dpusets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - provisioning.dpf.nvidia.com
  resources:
  - dpusets/finalizers
  verbs:
  - update
- apiGroups:
  - provisioning.dpf.nvidia.com
  resources:
  - dpusets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuservicechains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuservicechains/finalizers
  verbs:
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuservicechains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuserviceinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuserviceinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuserviceinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuserviceipams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuserviceipams/finalizers
  verbs:
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - dpuserviceipams/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - servicechains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - servicechains/finalizers
  verbs:
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - servicechains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - serviceinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - serviceinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - sfc.dpf.nvidia.com
  resources:
  - serviceinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - svc.dpf.nvidia.com
  resources:
  - dpuservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - svc.dpf.nvidia.com
  resources:
  - dpuservices/finalizers
  verbs:
  - update
- apiGroups:
  - svc.dpf.nvidia.com
  resources:
  - dpuservices/status
  verbs:
  - get
  - patch
  - update
