# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/sfc.dpf.nvidia.com_serviceinterfaces.yaml
- bases/sfc.dpf.nvidia.com_serviceinterfacesets.yaml
- bases/sfc.dpf.nvidia.com_servicechains.yaml
- bases/sfc.dpf.nvidia.com_servicechainsets.yaml
- bases/sfc.dpf.nvidia.com_dpuservicechains.yaml
- bases/sfc.dpf.nvidia.com_dpuserviceinterfaces.yaml
- bases/sfc.dpf.nvidia.com_dpuserviceipams.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_serviceinterfaces.yaml
#- path: patches/webhook_in_serviceinterfacesets.yaml
#- path: patches/webhook_in_servicechains.yaml
#- path: patches/webhook_in_servicechainsets.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_serviceinterfaces.yaml
#- path: patches/cainjection_in_serviceinterfacesets.yaml
#- path: patches/cainjection_in_servicechains.yaml
#- path: patches/cainjection_in_servicechainsets.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

#configurations:
#- kustomizeconfig.yaml
