# Adds namespace to all resources.
namespace: dpf-operator-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: dpf-ovn-kubernetes-operator-
resources:
- ../crd
- ../rbac
- ../manager
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      dpf.nvidia.com/component: dpf-ovn-kubernetes-operator-controller-manager
