apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
images:
- name: controller
  newName: example.com/dpf-ovn-kubernetes-operator-controller-manager
  newTag: v0.1.0
