apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "snap-dpu.roleName" . }}
  labels:
    {{- include "snap-dpu.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "storage.dpu.nvidia.com"
  resources:
  - volumeattachments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "storage.dpu.nvidia.com"
  resources:
  - volumeattachments/finalizers
  verbs:
  - update
- apiGroups:
  - "storage.dpu.nvidia.com"
  resources:
  - volumeattachments/status
  verbs:
  - get
  - patch
  - update
