apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "snap-dpu.fullname" . }}-node-driver
  labels:
    {{- include "snap-dpu.labels" . | nindent 4 }}
    {{- with .Values.serviceDaemonSet.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.serviceDaemonSet.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "snap-dpu.selectorLabels" . | nindent 6 }}
  {{- with .Values.serviceDaemonSet.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "snap-dpu.selectorLabels" . | nindent 8 }}
        {{- with .Values.serviceDaemonSet.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.serviceDaemonSet.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.serviceDaemonSet.imagePullSecrets | default list }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.snapNodeDriver.podSecurityContext | nindent 8 }}
      {{- with .Values.serviceDaemonSet.nodeSelector | default dict }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceDaemonSet.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceDaemonSet.tolerations | default list }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "snap-dpu.serviceAccountName" . }}
      containers:
        - name: snap-node-driver
          image: "{{ .Values.snapNodeDriver.image.repository }}:{{ .Values.snapNodeDriver.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.snapNodeDriver.pullPolicy }}
          env:
            {{- range .Values.snapNodeDriver.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.snapNodeDriver.resources | nindent 12 }}