# Adds namespace to all resources.
namespace: dpf-operator

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: dpf-operator-

resources:
- resources/dpf-operator.clusterserviceversion.yaml
- ../operator/default
- ../operator/samples
- ../dpuservice/crd
- ../servicechainset/crd
- ../dpf-provisioning/crd
- ../argocd/crd

patchesStrategicMerge:
- operator_imagepullsecrets_patch.yaml
