---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snap-controller-role
rules:
- apiGroups:
  - "storage.dpu.nvidia.com"
  resources:
  - volumes
  - volumes/status
  - volumes/finalizers
  - volumeattachments
  - svvolumeattachments
  - volumeattachments/status
  - volumeattachments/finalizers
  - svvolumeattachments/status
  - storagepolicies
  - storagepolicies/status
  - storagevendors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: 
  - "storage.k8s.io"
  resources: 
  - "storageclasses"
  - "csidrivers"
  verbs:
  - "get"
  - "list"
  - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: snap-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: snap-controller-role
subjects:
  - kind: ServiceAccount
    name: snap-controller-sa
    namespace: dpf-operator-system
