apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dpf-operator-system
resources:
- daemonset.yaml
images:
- name: controller
  newName: nvidia.com/dpu-cni-provisioner
  newTag: dev
