{
 "title": "DOCA Platform Foundation State",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dpu_conditions",
    "label": "DPU Conditions",
    "query": {
     "query": "label_values(dpu_status_conditions,type)"
    }
   },
   {
    "name": "dpuservice_conditions",
    "label": "DPUService Conditions",
    "query": {
     "query": "label_values(dpuservice_status_conditions,type)"
    }
   },
   {
    "name": "dpfoperatorconfig_conditions",
    "label": "DPFOperatorConfig Conditions",
    "query": {
     "query": "label_values(dpfoperatorconfig_status_conditions,type)"
    }
   },
   {
    "name": "dpuserviceinterface_conditions",
    "label": "DPUServiceInterface Conditions",
    "query": {
     "query": "label_values(dpuserviceinterface_status_conditions,type)"
    }
   },
   {
    "name": "dpuservicechain_conditions",
    "label": "DPUServiceChain Conditions",
    "query": {
     "query": "label_values(dpuservicechain_status_conditions,type)"
    }
   },
   {
    "name": "dpuserviceipam_conditions",
    "label": "DPUServiceIPAM Conditions",
    "query": {
     "query": "label_values(dpuserviceipam_status_conditions,type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DPUService",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuservice_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuservice_status_conditions{type=\"Ready\"}) by (uid))",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuservice_status_conditions{type=\"Ready\"}) by (uid))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpu_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpu_status_conditions{type=\"Ready\"}) by (uid)) or vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpu_status_conditions{type=\"Initialized\"}) by (uid))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "BFB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(bfb_status_phase{phase=\"Ready\"} == 1) by (uid)) * 100 / count(max(bfb_status_phase{phase=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "count(max(bfb_status_phase{phase=\"Ready\"}) by (uid))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPFOperatorConfig",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpfoperatorconfig_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpfoperatorconfig_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpfoperatorconfig_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUServiceInterface",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuserviceinterface_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuserviceinterface_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuserviceinterface_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUServiceIPAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuserviceipam_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuserviceipam_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuserviceipam_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUServiceChain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(dpuservicechain_status_conditions{type=\"Ready\",status=\"True\"}) by (uid)) * 100 / sum(max(dpuservicechain_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(max(dpuservicechain_status_conditions{type=\"Ready\"}) by (uid)) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DPUServices",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "dpuservice_info{}", "legendFormat": "Auto" },
    {
     "expr": "dpuservice_status_conditions{type=\"Ready\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DPUs",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "targets": [
    { "expr": "dpu_info{}", "legendFormat": "Auto" }
   ]
  },
  {
   "title": "Performance > DPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPU time until $dpu_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "repeat": "dpu_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpu_status_condition_last_transition_time{status=\"True\",type=\"$dpu_conditions\"} - on(uid) group_left () dpu_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUService time until $dpuservice_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "repeat": "dpuservice_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpuservice_status_condition_last_transition_time{status=\"True\",type=\"$dpuservice_conditions\"} - on(uid) group_left () dpuservice_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPFOperatorConfig",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPFOperatorConfig time until $dpfoperatorconfig_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "repeat": "dpfoperatorconfig_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpfoperatorconfig_status_condition_last_transition_time{status=\"True\",type=\"$dpfoperatorconfig_conditions\"} - on(uid) group_left () dpfoperatorconfig_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUServiceInterface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUServiceInterface time until $dpuserviceinterface_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "repeat": "dpuserviceinterface_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpuserviceinterface_status_condition_last_transition_time{status=\"True\",type=\"$dpuserviceinterface_conditions\"} - on(uid) group_left () dpuserviceinterface_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUServiceIPAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUServiceIPAM time until $dpuserviceipam_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "repeat": "dpuserviceipam_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpuserviceipam_status_condition_last_transition_time{status=\"True\",type=\"$dpuserviceipam_conditions\"} - on(uid) group_left () dpuserviceipam_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance > DPUServiceChain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPUServiceChain time until $dpuservicechain_conditions since creationTimestamp",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "repeat": "dpuservicechain_conditions",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(dpuservicechain_status_condition_last_transition_time{status=\"True\",type=\"$dpuservicechain_conditions\"} - on(uid) group_left () dpuservicechain_created{}) by (uid, name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Conditions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPU by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
     "targets": [
      { "expr": "sum (dpu_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpu_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpu_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPFOperatorConfig by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
     "targets": [
      { "expr": "sum (dpfoperatorconfig_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpfoperatorconfig_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpfoperatorconfig_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUService by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
     "targets": [
      { "expr": "sum (dpuservice_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpuservice_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpuservice_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUServiceChain by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
     "targets": [
      { "expr": "sum (dpuservicechain_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpuservicechain_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpuservicechain_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUServiceInterface by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
     "targets": [
      { "expr": "sum (dpuserviceinterface_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpuserviceinterface_status_conditions{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpuserviceinterface_status_conditions{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    },
    {
     "title": "DPUServiceIPAM by conditions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
     "targets": [
      { "expr": "sum (dpuserviceipam_info)", "legendFormat": "All" },
      {
       "expr": "sum(dpuserviceipam_status_condition{status=\"True\"} == 1) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(dpuserviceipam_status_condition{status=\"False\"} == 1) by (type)",
       "legendFormat": "{{type}} (False)"
      }
     ]
    }
   ]
  },
  {
   "title": "Phases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "DPU by status phase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(dpu_status_phase == 1) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "BFB by status phase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
     "targets": [
      {
       "expr": "sum(bfb_status_phase == 1) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    }
   ]
  }
 ]
}