# permissions for end users to view dpuclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: cluster-manager
  name: dpucluster-viewer-role
rules:
- apiGroups:
  - cluster-manager.dpu.nvidia.com
  resources:
  - dpuclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster-manager.dpu.nvidia.com
  resources:
  - dpuclusters/status
  verbs:
  - get
