## Images built as part of the DPF release.
dmsImage: example.com/dms-server:v0.1.0
hostNetworkSetupImage: example.com/hostnetworksetup:v0.1.0
dpfSystemImage: example.com/dpf-system:v0.1.0
sfcControllerImage: example.com/sfc-controller-manager:v0.1.0
ipAllocatorImage: example.com/ip-allocator:v0.1.0

## Helm charts built as part of the DPF release.
dpuNetworkingHelmChart: oci://example.com/dpu-networking:v0.1.0

## These images are no longer published with the DPF release process. They should only be used from the demo release tag.
customOVNKubernetesDPUImage: example.com/ovn-kubernetes-dpu:v0.1.0
customOVNKubernetesNonDPUImage: example.com/ovn-kubernetes-non-dpu:v0.1.0
