# Adds namespace to all resources.
namespace: dpf-operator-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: dpf-operator-

labels:
  - includeTemplates: true
    includeSelectors: true
    pairs:
      dpu.nvidia.com/component: servicefunctionchainset-controller-manager

resources:
- ../crd
- ../rbac
- ../manager
