apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: mybrsfc
  annotations:
    k8s.v1.cni.cncf.io/resourceName: nvidia.com/bf_sf
  labels:
    {{- include "multus.labels" . | nindent 4 }}
spec:
  config: |-
    {
      "cniVersion": "0.4.0",
      "type": "ovs",
      "bridge": "br-sfc",
      "mtu": {{ .Values.mtu }},
      "interface_type": "dpdk",
      "ipam": {
        "type": "nv-ipam"
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: mybrhbn
  annotations:
    k8s.v1.cni.cncf.io/resourceName: nvidia.com/bf_sf
  labels:
    {{- include "multus.labels" . | nindent 4 }}
spec:
  config: |-
    {
      "cniVersion": "0.4.0",
      "type": "ovs",
      "mtu": {{ .Values.mtu }},
      "bridge": "br-hbn",
      "interface_type": "dpdk"
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: iprequest
  labels:
    {{- include "multus.labels" . | nindent 4 }}
spec:
  config: |-
    {
      "cniVersion": "0.4.0",
      "type": "dummy",
      "ipam": {
        "type": "nv-ipam"
      }
    }
