apiVersion: v1
kind: ServiceAccount
metadata:
  name: multus
  labels:
  {{- include "multus.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.multus.serviceAccount.annotations | nindent 4 }}