---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snap-node-driver-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - storage.nvidia.com
  resources:
  - volumeattachments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.nvidia.com
  resources:
  - volumeattachments/finalizers
  verbs:
  - update
- apiGroups:
  - storage.nvidia.com
  resources:
  - volumeattachments/status
  verbs:
  - get
  - patch
  - update
