# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/provisioning.dpu.nvidia.com_dpus.yaml
- bases/provisioning.dpu.nvidia.com_dpusets.yaml
- bases/provisioning.dpu.nvidia.com_bfbs.yaml
- bases/provisioning.dpu.nvidia.com_dpuflavors.yaml
- bases/provisioning.dpu.nvidia.com_dpuclusters.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- path: patches/webhook_in_dpus.yaml
#- path: patches/webhook_in_dpusets.yaml
#- path: patches/webhook_in_bfbs.yaml
#- path: patches/webhook_in_dpuflavors.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_dpus.yaml
#- path: patches/cainjection_in_dpusets.yaml
#- path: patches/cainjection_in_bfbs.yaml
#- path: patches/cainjection_in_dpuflavors.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
