# permissions for end users to edit dpfovnkubernetesoperatorconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dpfovnkubernetesoperatorconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dpf-operator
    app.kubernetes.io/part-of: dpf-operator
    app.kubernetes.io/managed-by: kustomize
  name: dpfovnkubernetesoperatorconfig-editor-role
rules:
- apiGroups:
  - ovn.dpu.nvidia.com
  resources:
  - dpfovnkubernetesoperatorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ovn.dpu.nvidia.com
  resources:
  - dpfovnkubernetesoperatorconfigs/status
  verbs:
  - get
