---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ovn.dpf.nvidia.com
  resources:
  - dpfovnkubernetesoperatorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ovn.dpf.nvidia.com
  resources:
  - dpfovnkubernetesoperatorconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - ovn.dpf.nvidia.com
  resources:
  - dpfovnkubernetesoperatorconfigs/status
  verbs:
  - get
  - patch
  - update
