apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sfc-controller.fullname" . }}-node
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dpf-operator
    app.kubernetes.io/part-of: dpf-operator
  {{- include "sfc-controller.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}