apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: dpuservice-controller-manager
    dpu.nvidia.com/component: dpuservice-controller-manager
  name: dpuservice-controller-manager
  namespace: dpuservice-controller-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/part-of: dpuservice-controller-manager
    dpu.nvidia.com/component: dpuservice-controller-manager
  name: dpuservice-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kamaji.clastix.io
  resources:
  - tenantcontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nv-ipam.nvidia.com
  resources:
  - ippools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.dpu.nvidia.com
  resources:
  - dpfoperatorconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.dpu.nvidia.com
  resources:
  - dpfoperatorconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - bfbs
  - dpuflavors
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - bfbs/finalizers
  - dpuflavors/finalizers
  verbs:
  - update
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - dpuclusters
  - dpus
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - dpusets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - dpudeployments
  - dpuserviceconfigurations
  - dpuservicetemplates
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - dpudeployments/finalizers
  - dpuservicechains/finalizers
  - dpuservicecredentialrequests/finalizers
  - dpuserviceinterfaces/finalizers
  - dpuserviceipams/finalizers
  - dpuservicenads/finalizers
  - dpuservices/finalizers
  - dpuservicetemplates/finalizers
  verbs:
  - update
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - dpudeployments/status
  - dpuservicechains/status
  - dpuservicecredentialrequests/status
  - dpuserviceinterfaces/status
  - dpuserviceipams/status
  - dpuservicenads/status
  - dpuservices/status
  - dpuservicetemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - dpuservicechains
  - dpuserviceinterfaces
  - dpuservices
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - svc.dpu.nvidia.com
  resources:
  - dpuservicecredentialrequests
  - dpuserviceipams
  - dpuservicenads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: dpuservice-controller-manager
    dpu.nvidia.com/component: dpuservice-controller-manager
  name: dpuservice-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dpuservice-manager-role
subjects:
- kind: ServiceAccount
  name: dpuservice-controller-manager
  namespace: dpuservice-controller-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: dpuservice-controller-manager
    dpu.nvidia.com/component: dpuservice-controller-manager
  name: dpuservice-leader-election-role
  namespace: dpuservice-controller-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: dpuservice-controller-manager
    dpu.nvidia.com/component: dpuservice-controller-manager
  name: dpuservice-leader-election-rolebinding
  namespace: dpuservice-controller-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dpuservice-leader-election-role
subjects:
- kind: ServiceAccount
  name: dpuservice-controller-manager
  namespace: dpuservice-controller-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/part-of: dpuservice-controller-manager
    dpu.nvidia.com/component: dpuservice-controller-manager
  name: dpuservice-webhook-service
  namespace: dpuservice-controller-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/part-of: dpuservice-controller-manager
    dpu.nvidia.com/component: dpuservice-controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/part-of: dpuservice-controller-manager
    dpu.nvidia.com/component: dpuservice-controller-manager
  name: dpuservice-controller-manager
  namespace: dpuservice-controller-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: dpuservice-controller-manager
      dpu.nvidia.com/component: dpuservice-controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/part-of: dpuservice-controller-manager
        dpu.nvidia.com/component: dpuservice-controller-manager
    spec:
      containers:
      - command:
        - /dpuservice
        - --leader-elect
        image: example.com/dpf-system:v0.1.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      serviceAccountName: dpuservice-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: dpuservice-webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/part-of: dpuservice-controller-manager
    dpu.nvidia.com/component: dpuservice-controller-manager
  name: dpuservice-serving-cert
  namespace: dpuservice-controller-system
spec:
  dnsNames:
  - dpuservice-webhook-service.dpuservice-controller-system.svc
  - dpuservice-webhook-service.dpuservice-controller-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: dpuservice-selfsigned-issuer
  secretName: dpuservice-webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/part-of: dpuservice-controller-manager
    dpu.nvidia.com/component: dpuservice-controller-manager
  name: dpuservice-selfsigned-issuer
  namespace: dpuservice-controller-system
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: dpuservice-controller-system/dpuservice-serving-cert
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/part-of: dpuservice-controller-manager
    dpu.nvidia.com/component: dpuservice-controller-manager
  name: dpuservice-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: dpuservice-webhook-service
      namespace: dpuservice-controller-system
      path: /validate-svc-dpu-nvidia-com-v1alpha1-dpuserviceipam
  failurePolicy: Fail
  name: ipam-validator.svc.dpu.nvidia.com
  rules:
  - apiGroups:
    - svc.dpu.nvidia.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dpuserviceipams
  sideEffects: None
