apiVersion: svc.dpf.nvidia.com/v1alpha1
kind: DPUService
metadata:
  name: flannel
  namespace: dpf-operator-system
spec:
  helmChart:
    source:
      repoURL: example.com
      chart: flannel
      version: v0.25.1
    values:
      podCidr: "10.36.0.0/16"
