apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUService
metadata:
  name: ovs-helper
  namespace: dpf-operator-system
spec:
  helmChart:
    source:
      repoURL: oci://example.com
      chart: ovs-helper-chart
      version: v0.1.0

