---
apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUServiceTemplate
metadata:
  name: ovn
  namespace: dpf-operator-system
spec:
  deploymentServiceName: "ovn"
  helmChart:
    source:
      repoURL: $OVN_KUBERNETES_REPO_URL
      chart: ovn-kubernetes-chart
      version: $TAG
    values:
      ovn-kubernetes-resource-injector:
        enabled: false
      nodeWithDPUManifests:
        enabled: false
      nodeWithoutDPUManifests:
        enabled: false
      controlPlaneManifests:
        enabled: false
      dpuManifests:
        enabled: true
      gatewayOpts: "--gateway-interface=br-ovn --gateway-uplink-port=puplinkbrovn"
      global:
        imagePullSecretName: dpf-pull-secret
