apiVersion: v2
name: dpf-operator
description: DPF Operator managed the lifecycle of a DOCA Platform Foundation system.
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: argo-cd
    version: "6.10.0"
    repository: "https://argoproj.github.io/argo-helm"
    condition: argo-cd.enabled
  - name: node-feature-discovery
    version: "0.16.4"
    repository: "https://kubernetes-sigs.github.io/node-feature-discovery/charts"
    condition: node-feature-discovery.enabled
