controllerManager:
  manager:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: example.com/dpf-operator-controller-manager
      tag: v0.1.0
  replicas: 1
  serviceAccount:
    annotations: {}
imagePullSecrets: []
kubernetesClusterDomain: cluster.local
