## argo-cd and kamaji are installed as dependencies and configured here.
argo-cd:
  enabled: true
  dex:
    enabled: false
  notifications:
    enabled: false

controllerManager:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
  image:
    repository: example.com/dpf-system
    tag: v0.1.0
  replicas: 1
  serviceAccount:
    annotations: {}
imagePullSecrets: []
