## argo-cd, node-feature-discovery and kube-state-metrics are installed as dependencies and configured here.
argo-cd:
  enabled: true
  dex:
    enabled: false
  notifications:
    enabled: false
node-feature-discovery:
  enabled: true
kube-state-metrics:
  enabled: false
grafana:
  enabled: false
prometheus:
  enabled: false
  # We have to disable kube-state-metrics that is a dependency from Prometheus.
  # Adding KSM manually has the benefit that we can only enable KSM, without Prometheus.
  kube-state-metrics:
    enabled: false
kamaji-etcd:
  enabled: true
  datastore:
    enabled: true
    name: default
kamaji:
  enabled: true
  etcd:
    deploy: false
  datastore:
    enabled: false
    nameOverride: default
  image:
    pullPolicy: IfNotPresent
  cfssl:
    image:
      tag: v1.6.5

  

controllerManager:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
  image:
    repository: example.com/dpf-system
    tag: v0.1.0
  replicas: 1
  serviceAccount:
    annotations: {}
imagePullSecrets: []
