---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: manager
  name: webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    
