---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kamaji-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kamaji-pv-1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kamaji-storage
  nfs:
    path: /mnt/dpf_share/pv1
    server: $NFS_SERVER_IP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kamaji-pv-2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kamaji-storage
  nfs:
    path: /mnt/dpf_share/pv2
    server: $NFS_SERVER_IP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kamaji-pv-3
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kamaji-storage
  nfs:
    path: /mnt/dpf_share/pv3
    server: $NFS_SERVER_IP
