apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dpf-operator-system
namePrefix: dpf-operator-
resources:
  - ../dpuservice/crd
  - ../provisioning/crd
  - operator.dpu.nvidia.com_dpfoperatorconfigs.yaml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      dpu.nvidia.com/component: dpf-operator-controller-manager
      app.kubernetes.io/part-of: dpf-operator-controller-manager
