- groupVersionKind:
    group: svc.dpf.nvidia.com
    kind: DPUServiceCredentialRequest
    version: v1alpha1
  labelsFromPath:
    name:
      - metadata
      - name
    namespace:
      - metadata
      - namespace
    uid:
      - metadata
      - uid
  metricNamePrefix: dpuservicecredentialrequest
  metrics:
    - name: created
      help: Unix creation timestamp.
      each:
        gauge:
          path:
            - metadata
            - creationTimestamp
        type: Gauge
    - name: info
      help: Information about a DPUServiceCredentialRequest.
      each:
        type: Info
        info:
          labelsFromPath:
            name:
              - metadata
              - name
            type:
              - spec
              - type
            target_cluster_name:
              - status
              - targetClusterName
            service_account:
              - status
              - serviceAccount
            secret:
              - status
              - secret
    - name: duration
      help: The duration of a DPUServiceCredentialRequest.
      each:
        gauge:
          nilIsZero: true
          path:
            - spec
          valueFrom:
            - duration
        type: Gauge
    - name: expiration
      help: The expiration of a DPUServiceCredentialRequest.
      each:
        gauge:
          nilIsZero: true
          path:
            - status
          valueFrom:
            - expirationTimestamp
        type: Gauge
    - name: issued_at
      help: The time when the token was issued of a DPUServiceCredentialRequest.
      each:
        gauge:
          nilIsZero: true
          path:
            - status
          valueFrom:
            - issuedAt
        type: Gauge
    - name: status_conditions
      help: The condition of a DPUServiceCredentialRequest.
      each:
        stateSet:
          labelName: status
          labelsFromPath:
            type:
              - type
          list:
            - 'True'
            - 'False'
            - Unknown
          path:
            - status
            - conditions
          valueFrom:
            - status
        type: StateSet
    - name: status_condition_last_transition_time
      help: The condition last transition time of a DPUServiceCredentialRequest.
      each:
        gauge:
          nilIsZero: true
          labelsFromPath:
            type:
              - type
            status:
              - status
          path:
            - status
            - conditions
          valueFrom:
            - lastTransitionTime
        type: Gauge
