/*
COPYRIGHT 2024 NVIDIA

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package ovsmodel

const FlowTableTable = "Flow_Table"

type (
	FlowTableOverflowPolicy = string
)

var (
	FlowTableOverflowPolicyEvict  FlowTableOverflowPolicy = "evict"
	FlowTableOverflowPolicyRefuse FlowTableOverflowPolicy = "refuse"
)

// FlowTable defines an object in Flow_Table table
type FlowTable struct {
	UUID           string                   `ovsdb:"_uuid"`
	ExternalIDs    map[string]string        `ovsdb:"external_ids"`
	FlowLimit      *int                     `ovsdb:"flow_limit"`
	Groups         []string                 `ovsdb:"groups"`
	Name           *string                  `ovsdb:"name"`
	OverflowPolicy *FlowTableOverflowPolicy `ovsdb:"overflow_policy"`
	Prefixes       []string                 `ovsdb:"prefixes"`
}
