---
apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUService
metadata:
  name: snap-csi-plugin
  namespace: dpf-operator-system
spec:
  serviceID: snap-csi-plugin
  deployInCluster: true
  helmChart:
    source:
      repoURL: oci://$DPF_REGISTRY
      version: $DPF_VERSION
      chart: snap-csi-plugin-chart
    values:
      image:
        repository: $DPF_REGISTRY/snap-csi-plugin
        tag: $DPF_VERSION
      imagePullSecrets: $DPF_IMAGE_PULL_SECRET
      controller:
        config:
          # required parameter, name of the secret that contains connection
          # details to access the DPU cluster.
          # this secret should be created by the DPUServiceCredentialRequest API.
          dpuClusterSecret: snap-csi-plugin-dpu-cluster-credentials
          # required parameter, target namespace in the DPU cluster to create storage-related CRs
          targetNamespace: dpf-operator-system
