# Adds namespace to all resources.
namespace: dpuservice-controller-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: dpuservice-

labels:
  - includeTemplates: true
    includeSelectors: true
    pairs:
      dpf.nvidia.com/component: dpuservice-controller-manager

resources:
- ../crd
- ../rbac
- ../manager

